In [153]:
#CBOW
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [154]:
pwd

'C:\\Users\\ARPITA'

In [155]:
lines = ['It was a nice rainy day', 'The things are so beautiful in his point.', 'When your focus is clear, you won.', 'Many many happy returns of the day.']

In [156]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)

In [157]:
tokenizer.word_docs

defaultdict(int,
            {'day': 2,
             'was': 1,
             'it': 1,
             'rainy': 1,
             'a': 1,
             'nice': 1,
             'things': 1,
             'the': 2,
             'are': 1,
             'point': 1,
             'so': 1,
             'beautiful': 1,
             'in': 1,
             'his': 1,
             'is': 1,
             'your': 1,
             'you': 1,
             'won': 1,
             'clear': 1,
             'when': 1,
             'focus': 1,
             'of': 1,
             'many': 1,
             'returns': 1,
             'happy': 1})

In [158]:
tokenizer.word_index

{'day': 1,
 'the': 2,
 'many': 3,
 'it': 4,
 'was': 5,
 'a': 6,
 'nice': 7,
 'rainy': 8,
 'things': 9,
 'are': 10,
 'so': 11,
 'beautiful': 12,
 'in': 13,
 'his': 14,
 'point': 15,
 'when': 16,
 'your': 17,
 'focus': 18,
 'is': 19,
 'clear': 20,
 'you': 21,
 'won': 22,
 'happy': 23,
 'returns': 24,
 'of': 25}

In [159]:
mat = tokenizer.texts_to_matrix(lines)
mat

array([[0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [160]:
seq = tokenizer.texts_to_sequences(lines)
seq

[[4, 5, 6, 7, 8, 1],
 [2, 9, 10, 11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20, 21, 22],
 [3, 3, 23, 24, 25, 2, 1]]

In [161]:
padded = pad_sequences(seq, maxlen=10, padding='pre')
padded

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  1],
       [ 0,  0,  2,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  0,  0, 16, 17, 18, 19, 20, 21, 22],
       [ 0,  0,  0,  3,  3, 23, 24, 25,  2,  1]])

In [162]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM
from sklearn.model_selection import train_test_split
import re
import numpy as np


In [163]:
data = pd.read_csv(r"C:\Users\ARPITA\Downloads\twitter_sentiments.csv", names=['id', 'loc', 'label', 'text'])

In [164]:
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
74677  Just realized that the Windows partition of my...  
74678  Just realized that my Mac window partition is ...  
74679  Just realized the windows partition of my Mac ...  
74680  Just realized between the windows partition of...  
74681  Just like the windows partition of my Mac is l...  

[74682 rows x 4 columns]

In [165]:
data.shape

(74682, 4)

In [166]:
data.dtypes

id        int64
loc      object
label    object
text     object
dtype: object

In [167]:
data['text']=data['text'].astype(str)

In [168]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]+', ' ', text)
    return text

In [169]:
data['text'] = data['text'].apply(clean_text)

In [170]:
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      i am coming to the borders and i will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands and i will murder yo...  
...                                                  ...  
74677  just realized that the windows partition of my...  
74678  just realized that my mac window partition is ...  
74679  just realized the windows partition of my mac ...  
74680  just realized between the windows partition of...  
74681  just like the windows partition of my mac is l...  

[74682 rows x 4 columns]

In [171]:
#feature and target preparation 
comments = data['text'].tolist()
target = data['label'].values

In [172]:
np.unique(target)

array(['Irrelevant', 'Negative', 'Neutral', 'Positive'], dtype=object)

In [173]:
#tokenization and padding
Tokenizer = Tokenizer(num_words=5000)
Tokenizer.fit_on_texts(comments)
sequences = Tokenizer.texts_to_sequences(comments)
padded_sequences = pad_sequences(sequences, maxlen=200)

In [174]:
padded_sequences.shape

(74682, 200)

In [175]:
padded_sequences

array([[   0,    0,    0, ..., 1695,   12,   26],
       [   0,    0,    0, ...,  424,   12,   26],
       [   0,    0,    0, ...,  424,   12,   26],
       ...,
       [   0,    0,    0, ...,  302,   15, 2055],
       [   0,    0,    0, ...,  302,   15, 2055],
       [   0,    0,    0, ...,  302,   15, 2055]])

In [176]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(target)

from keras.utils import to_categorical
y_new = to_categorical(y)

In [177]:
y_new

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [178]:
y_new.shape

(74682, 4)

In [179]:
from collections import Counter
Counter(target)

Counter({'Negative': 22542,
         'Positive': 20832,
         'Neutral': 18318,
         'Irrelevant': 12990})

In [180]:
#train test split 
x_train, x_test, y_train, y_test = train_test_split(padded_sequences, y_new, test_size = 0.2)

In [181]:
x_train.shape

(59745, 200)

In [182]:
x_test.shape

(14937, 200)

In [186]:
#model definition
model = Sequential()
model.add(Embedding(5000, 100, input_length =200))
model.add(LSTM(64))
model.add(Dense(4, activation='sigmoid'))          

In [187]:
#compile the model
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [188]:
#train the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, batch_size = 32)

Epoch 1/5
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 101s 53ms/step - accuracy: 0.5316 - loss: 1.0822 - val_accuracy: 0.6864 - val_loss: 0.8014
Epoch 2/5
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 98s 52ms/step - accuracy: 0.7390 - loss: 0.6683 - val_accuracy: 0.7445 - val_loss: 0.6636
Epoch 3/5
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 97s 52ms/step - accuracy: 0.8126 - loss: 0.4875 - val_accuracy: 0.7830 - val_loss: 0.5822
Epoch 4/5
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 97s 52ms/step - accuracy: 0.8545 - loss: 0.3812 - val_accuracy: 0.8040 - val_loss: 0.5478
Epoch 5/5
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 98s 52ms/step - accuracy: 0.8840 - loss: 0.3064 - val_accuracy: 0.8200 - val_loss: 0.5292


In [192]:
#Prediction on unseen comment
new_comment = 'I hate him'
new_sequence = tokenizer.texts_to_sequences([clean_text(new_comment)])
new_padded_sequences = pad_sequences(new_sequence, maxlen = 200)
prediction = model.predict(new_padded_sequences)[0]
le.inverse_transform([np.argmax(prediction)])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array(['Neutral'], dtype=object)